Added invalidate secret workflow to main

diff --git a/.github/workflows/update-secret-workflow.yaml b/.github/workflows/update-secret-workflow.yaml
--- a/.github/workflows/update-secret-workflow.yaml
+++ b/.github/workflows/update-secret-workflow.yaml
@@ -15,7 +15,7 @@ jobs:
           key_count=$(aws iam list-access-keys --user-name "${{ env.USER_NAME }}" \
           --query 'length(AccessKeyMetadata[])' --output text)
           if [[ "$key_count" == "2" ]]; then
-            echo "Error: Two active access keys found for application. Maximum of one active key is allowed." >&2
+            echo "Error: Two active access keys found for application. Maximum of one active key is allowed. Please execute invalidate-secret-workflow to delete older key." >&2
             exit 1
           fi
       - name: Create new token
