added count verify logic

diff --git a/.github/workflows/update-secret-workflow.yaml b/.github/workflows/update-secret-workflow.yaml
--- a/.github/workflows/update-secret-workflow.yaml
+++ b/.github/workflows/update-secret-workflow.yaml
@@ -8,8 +8,12 @@ jobs:
     steps:
       - name: Check Token Count
         run: |
-          aws iam list-access-keys --user-name at-cli \
-          --query 'length(AccessKeyMetadata[])' --output text
+          key_count=$(aws iam list-access-keys --user-name at-cli \
+          --query 'length(AccessKeyMetadata[])' --output text)
+          if [["$key_count" -eq "2"]]; then
+            echo "Error: Two active access keys found for application. Maximum of one active key is allowed." >&2
+            exit 1
+          fi
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
